### ISSUE TITLE
A good idea

### ISSUE THREAD

**Issue by HectorLiuk** [lacklock/NiceGesture#2]
Originally intended going to write  support oc，No longer need to use cumbersome selector reflection , but also solve the problem of separation of code.
Refer to your ideas.
Thanks

**Comment by lacklock** [comment]
i have used generic type. oc doesn't have this feature. anyway hope you coding fun.

**Comment by HectorLiuk** [comment]
I plan use to category,  block dynamically tied into a variable UIGestureRecognizer,then call this block.
I hope my idea will succeed.
